### ISSUE TITLE
Infografia ciclo de vida software 

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-1-infografia-Heidi-19#2]
[Infografia - Heidi Lucy Bautista Sanjuan 5USC .pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Heidi-19/files/9420066/Infografia.-.Heidi.Lucy.Bautista.Sanjuan.5USC.pdf)

**Comment by abicoronel** [comment]
calificación:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
